"""Production Adapter for Script Factory V1.2 + V9.3.1 Hybrid Visual Strategy.

Converts approved scripts and story bibles into broadcast-ready production projects:
- Hybrid Visual Strategy:
  - IMAGE_ONLY (~65-70%) vs VIDEO_RECOMMENDED (~30-35%)
  - Video Budgets: LOW (20-25%), BALANCED (30-35%, default), RICH (40%). Hard cap: 40%.
  - All scenes require image_prompt and image_file.
  - For IMAGE_ONLY: video_file = None, video_prompt = None, video_priority = None.
  - Video Priority: P1, P2, P3 for VIDEO_RECOMMENDED.
  - Critical reveal scenes prefer IMAGE_ONLY + slow push + overlay.
  - Overlay safety: exact text rendered in post-production.
- Backward compatibility:
  - Supports episode_v9_3.json and episode_v9_3_1.json.
  - visual_manifest_v9_3_1.json and visual_prompts_v9_3_1.csv.
  - User override does NOT mutate script or audio.
- STRICT SAFETY: NEVER mutates Audio Formula V1 or existing audio engine.
"""
from __future__ import annotations

import csv
import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from apps.script_factory.approval_gate import HumanApprovalGate
from apps.script_factory.models import ApprovalStatus, FullScript, StoryBible

logger = logging.getLogger("VieNeu.ProductionAdapter")

VISUAL_PROMPT_PREFIX = (
    "Vietnamese cinematic social mystery drama, photorealistic, natural Vietnamese faces, "
    "realistic skin, restrained acting, modern Vietnamese environment, muted natural colors, "
    "subtle cinematic lighting, 35mm documentary drama look, 16:9, no fantasy, no anime, "
    "no glamour, no watermark."
)

VIDEO_BUDGET_CAPS = {
    "LOW": 0.25,
    "BALANCED": 0.35,
    "RICH": 0.40,
}

HARD_CAP_VIDEO_RATIO = 0.40


class ProductionAdapter:
    """Adapts approved scripts into V9.3.1 hybrid visual production projects."""

    def __init__(self, episodes_root: Optional[Path] = None):
        self.episodes_root = Path(episodes_root) if episodes_root else Path("episodes")

    def adapt_to_v9_3_project(
        self,
        script: FullScript,
        story_bible: StoryBible,
        video_budget: str = "BALANCED",
    ) -> Path:
        """Converts an approved script to a V9.3.1 production directory."""
        # Enforce approval gate
        HumanApprovalGate.verify_can_send_to_production(script, story_bible)

        ep_dir = self.episodes_root / script.episode_id
        prod_dir = ep_dir / "production"
        prod_dir.mkdir(parents=True, exist_ok=True)

        images_dir = prod_dir / "manual_assets" / "images"
        videos_dir = prod_dir / "manual_assets" / "videos"
        output_dir = prod_dir / "output"
        images_dir.mkdir(parents=True, exist_ok=True)
        videos_dir.mkdir(parents=True, exist_ok=True)
        output_dir.mkdir(parents=True, exist_ok=True)

        # 1. Build episode_v9_3_1.json (Schema 3.2.1) & episode_v9_3.json
        v9_3_data = {
            "schema_version": "3.2.1",
            "project": {
                "title": f"Sau Cánh Cửa {script.episode_id} V9.3.1 Hybrid Visual",
                "episode_title": script.title,
                "language": "vi-VN",
                "tts_engine": "VieNeu-TTS-v3-Turbo",
                "sample_rate": 48000,
                "target_master_lufs": -14,
                "true_peak_db": -1,
                "format": "single_host_dynamic_documentary_storytelling",
                "target_duration_minutes": "10-13",
                "notes": f"Generated by Script Factory V1.2 from Story Bible {script.episode_id}.",
            },
            "characters": {
                script.host.get("id", "MINH"): {
                    "display_name": script.host.get("display_name", "Minh"),
                    "role": "MC / narrator",
                    "voice": script.host.get("voice", "Binh"),
                    "default_speed": 1.0,
                }
            },
            "audio_direction": {
                "room_tone": {"enabled": False},
                "voice_rule": f"Only {script.host.get('id', 'MINH')}/{script.host.get('voice', 'Binh')} for every segment.",
                "quote_rule": "Same voice for quotes; vary delivery/pause only, no pitch-shift.",
                "audience_rule": "Conversational and restrained.",
                "critical_reveal_rule": "Major reveal remains fully dry.",
                "music_strategy": "Sparse; continuous within same cue.",
                "dynamic_rule": "Dynamics come primarily from delivery speed, pauses, performance and sparse music—not large loudness jumps.",
                "master_target": "-14 LUFS integrated target, -1 dBTP true peak; preserve natural phrase dynamics before final loudnorm.",
                "profile_order": "HOOK -> NORMAL/MYSTERY/COMMENT -> REVEAL -> NORMAL -> ENDING",
                "reveal_rule": "All REVEAL segments are dry. Music must fade out before the first REVEAL line and may return only after the reveal block.",
            },
            "segments": [s.to_dict() for s in script.segments],
        }

        # Save both for complete compatibility
        for fname in ["episode_v9_3_1.json", "episode_v9_3.json"]:
            with open(prod_dir / fname, "w", encoding="utf-8") as f:
                json.dump(v9_3_data, f, ensure_ascii=False, indent=2)

        # 2. Build Hybrid Visual Scenes
        scenes = self._generate_visual_scenes(script, story_bible, video_budget=video_budget)
        manifest_data = {
            "manifest_version": "9.3.1",
            "episode_id": script.episode_id,
            "title": script.title,
            "video_budget": video_budget,
            "total_scenes": len(scenes),
            "production_summary": self.get_production_summary(scenes, video_budget=video_budget),
            "scenes": scenes,
        }

        for fname in ["visual_manifest_v9_3_1.json", "visual_manifest.json"]:
            with open(prod_dir / fname, "w", encoding="utf-8") as f:
                json.dump(manifest_data, f, ensure_ascii=False, indent=2)

        # 3. Export visual_prompts_v9_3_1.csv (15 columns as specified in Section 42)
        csv_headers = [
            "scene_id",
            "source_segments",
            "story_beat",
            "visible_characters",
            "location",
            "visual_mode",
            "motion_value",
            "video_priority",
            "visual_mode_reason",
            "image_file",
            "video_file",
            "image_prompt",
            "video_prompt",
            "overlay_text",
            "image_motion",
        ]

        for fname in ["visual_prompts_v9_3_1.csv", "visual_prompts.csv"]:
            with open(prod_dir / fname, "w", encoding="utf-8", newline="") as f:
                writer = csv.writer(f)
                writer.writerow(csv_headers)
                for sc in scenes:
                    writer.writerow([
                        sc["scene_id"],
                        ";".join(sc["source_segments"]),
                        sc["story_beat"],
                        ";".join(sc.get("visible_characters", [])),
                        sc["location"],
                        sc["visual_mode"],
                        sc["motion_value"],
                        sc.get("video_priority") or "",
                        sc.get("visual_mode_reason", ""),
                        sc["image_file"],
                        sc.get("video_file") or "",
                        sc["image_prompt"],
                        sc.get("video_prompt") or "",
                        sc.get("overlay_text") or "",
                        json.dumps(sc.get("image_motion", {})),
                    ])

        # 4. Copy character and location bibles
        char_file = ep_dir / "character_bible.json"
        if char_file.exists():
            (prod_dir / "character_bible.json").write_text(char_file.read_text(encoding="utf-8"), encoding="utf-8")

        loc_file = ep_dir / "location_bible.json"
        if loc_file.exists():
            (prod_dir / "location_bible.json").write_text(loc_file.read_text(encoding="utf-8"), encoding="utf-8")

        # 5. Record production.json in episode root
        prod_meta = {
            "episode_id": script.episode_id,
            "status": ApprovalStatus.PRODUCTION_READY,
            "production_dir": str(prod_dir),
            "episode_v9_3_1_json": str(prod_dir / "episode_v9_3_1.json"),
            "visual_manifest_v9_3_1_json": str(prod_dir / "visual_manifest_v9_3_1.json"),
            "total_scenes": len(scenes),
            "production_summary": self.get_production_summary(scenes, video_budget=video_budget),
        }
        with open(ep_dir / "production.json", "w", encoding="utf-8") as f:
            json.dump(prod_meta, f, ensure_ascii=False, indent=2)

        logger.info(f"[ProductionAdapter] Created V9.3.1 production package for {script.episode_id}.")
        return prod_dir

    def _generate_visual_scenes(
        self,
        script: FullScript,
        story_bible: StoryBible,
        video_budget: str = "BALANCED",
    ) -> List[Dict[str, Any]]:
        """Groups segments into 35-50 cinematic visual scenes and classifies visual mode."""
        segs = script.segments
        total_segs = len(segs)

        scenes: List[Dict[str, Any]] = []
        seg_idx = 0
        scene_idx = 1

        loc_candidates = story_bible.locations if story_bible.locations else ["HOME", "STREET", "OFFICE"]
        protagonist_name = story_bible.protagonist.get("name", "Nhân vật chính")

        while seg_idx < total_segs:
            chunk = segs[seg_idx : min(total_segs, seg_idx + 2)]
            chunk_ids = [s.id for s in chunk]
            beat_text = chunk[0].text[:80] + ("..." if len(chunk[0].text) > 80 else "")

            sc_id = f"SC_{scene_idx:03d}"
            loc = loc_candidates[(scene_idx - 1) % len(loc_candidates)]

            overlay_text = None
            is_reveal_chunk = any(s.delivery_profile == "REVEAL" for s in chunk)
            if is_reveal_chunk:
                for fact in story_bible.critical_facts:
                    if fact.status == "LOCKED" and (fact.value.lower() in chunk[0].text.lower() or (len(chunk) > 1 and fact.value.lower() in chunk[1].text.lower())):
                        overlay_text = f"{fact.field}: {fact.value}"
                        break
                if not overlay_text and story_bible.reveal_1 in chunk[0].text:
                    overlay_text = f"Xác nhận: {story_bible.reveal_1[:40]}"

            img_prompt = (
                f"{VISUAL_PROMPT_PREFIX} "
                f"Scene {sc_id} set in {loc}. "
                f"Protagonist {protagonist_name} ({story_bible.protagonist.get('age', 32)} years old, authentic domestic look). "
                f"Cinematic framing capturing emotional restraint and domestic mystery. 16:9 composition."
            )

            raw_scene = {
                "scene_id": sc_id,
                "scene_index": scene_idx,
                "source_segments": chunk_ids,
                "story_beat": beat_text,
                "visible_characters": [story_bible.protagonist.get("char_id", "PROTAGONIST")],
                "location": loc,
                "image_file": f"{sc_id}.png",
                "image_prompt": img_prompt,
                "overlay_text": overlay_text,
                "is_reveal": is_reveal_chunk,
                "delivery_profile": chunk[0].delivery_profile,
            }
            scenes.append(raw_scene)

            scene_idx += 1
            seg_idx += len(chunk)

        # Apply semantic classification and video budgeting
        classified_scenes = self.classify_scenes(scenes, video_budget=video_budget)
        return classified_scenes

    def classify_scenes(
        self,
        scenes: List[Dict[str, Any]],
        video_budget: str = "BALANCED",
    ) -> List[Dict[str, Any]]:
        """
        Semantically classifies scenes into IMAGE_ONLY or VIDEO_RECOMMENDED.
        Applies Video Budget cap and priority filtering.
        """
        budget_target_ratio = VIDEO_BUDGET_CAPS.get(video_budget, 0.35)
        total = len(scenes)
        if total <= 2:
            max_videos = total
        else:
            max_videos = int(total * min(budget_target_ratio, HARD_CAP_VIDEO_RATIO))

        candidates: List[Tuple[int, str, str, str, str]] = []  # (priority_rank, priority_label, motion_val, reason, vid_prompt)

        for idx, sc in enumerate(scenes):
            beat = sc.get("story_beat", "").lower()
            sc_id = sc.get("scene_id", f"SC_{idx+1:03d}")
            loc = sc.get("location", "HOME")
            is_reveal = sc.get("is_reveal", False)
            delivery = sc.get("delivery_profile", "NORMAL")

            # Section 34: IMAGE_ONLY Preferred Criteria
            # Documents, bank records, phone screens, SMS, letters, photos, receipts, cassette, evidence macro
            is_document = any(w in beat for w in ["giấy", "hồ sơ", "di chúc", "khai tử", "biên lai", "sao kê", "sổ tiết kiệm", "tin nhắn", "sms", "ảnh", "bức ảnh", "băng cassette", "điện thoại"])
            is_reflection = delivery in ["COMMENT", "ENDING"] or any(w in beat for w in ["suy ngẫm", "nhìn xa xăm", "hoàng hôn", "đứng lặng"])

            # Section 35: Critical Reveal is IMAGE_ONLY with slow push + overlay
            if is_reveal or is_document or is_reflection:
                sc["visual_mode"] = "IMAGE_ONLY"
                sc["motion_value"] = "LOW"
                sc["video_priority"] = None
                sc["video_file"] = None
                sc["video_prompt"] = None
                sc["visual_mode_reason"] = "Tập trung chi tiết chứng cứ / tài liệu / khoảng lặng suy ngẫm, tối ưu hiển thị overlay chữ."
                sc["image_motion"] = {"type": "SLOW_PUSH", "speed": "SLOW"}
                continue

            # Section 33: VIDEO_RECOMMENDED Criteria
            # Character interaction, confrontation, walking/searching, emotional reaction, embrace
            is_confrontation = any(w in beat for w in ["đối chất", "chất vấn", "tranh cãi", "thú nhận", "ôm", "khóc", "nghẹn ngào"])
            is_action_search = any(w in beat for w in ["bước đi", "tìm kiếm", "mở cửa", "chạy", "lần theo", "đến nhà"])
            is_hook_motion = delivery == "HOOK" or any(w in beat for w in ["mở đầu", "bắt đầu", "lá thư của lan mở đầu"])

            if is_confrontation or is_hook_motion:
                p_rank = 1
                p_label = "P1"
                m_val = "HIGH"
                reason = "Khoảnh khắc đối đầu / xúc động cao trào hoặc Hook hành động cần chuyển động kịch tính."
            elif is_action_search:
                p_rank = 2
                p_label = "P2"
                m_val = "MEDIUM"
                reason = "Hành động điều tra, di chuyển tìm kiếm manh mối thực địa."
            else:
                p_rank = 3
                p_label = "P3"
                m_val = "LOW"
                reason = "Tương tác nhân vật bối cảnh nhẹ nhàng."

            vid_prompt = (
                f"Slow deliberate camera movement in {loc}. "
                f"Subject subtly shifts posture, reflecting internal tension. "
                f"Preserve exact character identity and lighting. No erratic motion."
            )

            candidates.append((p_rank, p_label, m_val, reason, vid_prompt))
            sc["_temp_cand"] = (p_rank, p_label, m_val, reason, vid_prompt)

        # Allocate VIDEO_RECOMMENDED up to max_videos budget
        # Sort candidates by priority rank (P1 first, then P2, then P3)
        video_assigned = 0
        for sc in scenes:
            if sc.get("visual_mode") == "IMAGE_ONLY":
                continue

            p_rank, p_label, m_val, reason, vid_prompt = sc.pop("_temp_cand")
            sc_id = sc.get("scene_id")

            if video_assigned < max_videos and p_rank <= 2:
                sc["visual_mode"] = "VIDEO_RECOMMENDED"
                sc["motion_value"] = m_val
                sc["video_priority"] = p_label
                sc["video_file"] = f"{sc_id}.mp4"
                sc["video_prompt"] = vid_prompt
                sc["visual_mode_reason"] = reason
                sc["image_motion"] = {"type": "STATIC", "speed": "NORMAL"}
                video_assigned += 1
            else:
                # Fallback to IMAGE_ONLY due to budget cap
                sc["visual_mode"] = "IMAGE_ONLY"
                sc["motion_value"] = "LOW"
                sc["video_priority"] = None
                sc["video_file"] = None
                sc["video_prompt"] = None
                sc["visual_mode_reason"] = f"Ưu tiên ngân sách tĩnh (chuyển động nhẹ Ken Burns). Lý do gốc: {reason}"
                sc["image_motion"] = {"type": "PAN_RIGHT" if "P" in p_label else "SLOW_PUSH", "speed": "SLOW"}

        return scenes

    def get_production_summary(
        self,
        scenes: List[Dict[str, Any]],
        video_budget: str = "BALANCED",
    ) -> Dict[str, Any]:
        """Calculates production summary metrics conforming to Section 43."""
        total = len(scenes)
        img_only = sum(1 for s in scenes if s.get("visual_mode") == "IMAGE_ONLY")
        vid_rec = sum(1 for s in scenes if s.get("visual_mode") == "VIDEO_RECOMMENDED")
        p1 = sum(1 for s in scenes if s.get("video_priority") == "P1")
        p2 = sum(1 for s in scenes if s.get("video_priority") == "P2")
        p3 = sum(1 for s in scenes if s.get("video_priority") == "P3")
        ratio = round((vid_rec / total * 100.0) if total > 0 else 0.0, 1)

        return {
            "total_scenes": total,
            "images_required": total,
            "image_only_count": img_only,
            "video_recommended_count": vid_rec,
            "p1_count": p1,
            "p2_count": p2,
            "p3_count": p3,
            "video_ratio_pct": ratio,
            "video_budget": video_budget,
            "estimated_video_requests": vid_rec,
        }

    def override_scene_mode(
        self,
        manifest_data: Dict[str, Any],
        scene_id: str,
        new_mode: str,
    ) -> Dict[str, Any]:
        """
        User override: toggles IMAGE_ONLY <-> VIDEO_RECOMMENDED.
        Guaranteed: Does NOT mutate script, audio, Story Bible, or regenerate images.
        """
        scenes = manifest_data.get("scenes", [])
        for sc in scenes:
            if sc.get("scene_id") == scene_id:
                old_mode = sc.get("visual_mode")
                if new_mode == "IMAGE_ONLY":
                    sc["visual_mode"] = "IMAGE_ONLY"
                    sc["video_file"] = None
                    sc["video_prompt"] = None
                    sc["video_priority"] = None
                    sc["visual_mode_reason"] = f"Người dùng chuyển thủ công từ {old_mode} sang IMAGE_ONLY."
                    sc["image_motion"] = {"type": "SLOW_PUSH", "speed": "SLOW"}
                elif new_mode == "VIDEO_RECOMMENDED":
                    sc["visual_mode"] = "VIDEO_RECOMMENDED"
                    sc["video_file"] = f"{scene_id}.mp4"
                    sc["video_priority"] = sc.get("video_priority") or "P2"
                    sc["video_prompt"] = (
                        f"Slow deliberate camera movement in {sc.get('location', 'HOME')}. "
                        f"Subject subtly shifts posture, reflecting internal tension. "
                        f"Preserve exact character identity and lighting. No erratic motion."
                    )
                    sc["visual_mode_reason"] = f"Người dùng chuyển thủ công từ {old_mode} sang VIDEO_RECOMMENDED."
                    sc["image_motion"] = {"type": "STATIC", "speed": "NORMAL"}
                break

        manifest_data["production_summary"] = self.get_production_summary(
            scenes,
            video_budget=manifest_data.get("video_budget", "BALANCED"),
        )
        return manifest_data

    @staticmethod
    def resolve_assembler_asset(
        scene: Dict[str, Any],
        has_approved_video: bool = False,
    ) -> Dict[str, Any]:
        """
        Manual Visual Assembler decision rule (Section 47):
        if valid_approved_video_exists(scene): use_video() else: use_image_with_motion()
        """
        mode = scene.get("visual_mode", "IMAGE_ONLY")
        img_file = scene.get("image_file")
        vid_file = scene.get("video_file")

        if mode == "VIDEO_RECOMMENDED" and has_approved_video and vid_file:
            return {
                "chosen_asset": vid_file,
                "chosen_type": "VIDEO",
                "readiness": "READY",
            }
        else:
            return {
                "chosen_asset": img_file,
                "chosen_type": "IMAGE_WITH_MOTION",
                "readiness": "READY_WITH_IMAGE_FALLBACK" if mode == "VIDEO_RECOMMENDED" else "READY",
                "motion": scene.get("image_motion", {"type": "SLOW_PUSH", "speed": "SLOW"}),
            }


def migrate_ep001_to_v9_3_1(project_dir: Path, reports_dir: Optional[Path] = None) -> Dict[str, Any]:
    """
    Migrates EP001 V9.3 Golden Reference to V9.3.1 Hybrid Visual Strategy:
    - Preserves all 45 existing images.
    - Zero image regeneration, zero video requests, zero Flow calls.
    - Outputs visual_manifest_v9_3_1.json, visual_prompts_v9_3_1.csv, ep001_v9_3_1_visual_migration.json.
    - Leaves source.json and visual_manifest_v9_3.json completely untouched.
    """
    v9_3_file = project_dir / "visual_manifest_v9_3.json"
    if not v9_3_file.exists():
        raise FileNotFoundError(f"EP001 visual manifest not found at {v9_3_file}")

    with open(v9_3_file, "r", encoding="utf-8") as f:
        data_v9_3 = json.load(f)

    adapter = ProductionAdapter()
    scenes = data_v9_3.get("scenes", [])

    # Classify each scene into hybrid visual mode
    classified_scenes = adapter.classify_scenes(scenes, video_budget="BALANCED")

    # Build V9.3.1 manifest
    manifest_v9_3_1 = {
        "manifest_version": "9.3.1",
        "project_slug": data_v9_3.get("project_slug", "sau_canh_cua_ep01_v9_3_manual_visual"),
        "project_dir": str(project_dir),
        "audio_master_path": data_v9_3.get("audio_master_path", ""),
        "total_duration_sec": data_v9_3.get("total_duration_sec", 779.75),
        "timeline_source": data_v9_3.get("timeline_source", "PROJECT_AUDIO_SEGMENTS"),
        "video_budget": "BALANCED",
        "production_summary": adapter.get_production_summary(classified_scenes, video_budget="BALANCED"),
        "scenes": classified_scenes,
    }

    # Save visual_manifest_v9_3_1.json
    out_manifest = project_dir / "visual_manifest_v9_3_1.json"
    with open(out_manifest, "w", encoding="utf-8") as f:
        json.dump(manifest_v9_3_1, f, ensure_ascii=False, indent=2)

    # Save visual_prompts_v9_3_1.csv
    out_csv = project_dir / "visual_prompts_v9_3_1.csv"
    with open(out_csv, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "scene_id", "source_segments", "story_beat", "visible_characters", "location",
            "visual_mode", "motion_value", "video_priority", "visual_mode_reason",
            "image_file", "video_file", "image_prompt", "video_prompt", "overlay_text", "image_motion"
        ])
        for sc in classified_scenes:
            writer.writerow([
                sc.get("scene_id"),
                ";".join(sc.get("source_segment_ids", []) or sc.get("source_segments", [])),
                sc.get("story_beat", ""),
                ";".join(sc.get("visible_characters", [])),
                sc.get("location", "HOME"),
                sc.get("visual_mode"),
                sc.get("motion_value"),
                sc.get("video_priority") or "",
                sc.get("visual_mode_reason", ""),
                sc.get("image_file", f"{sc.get('scene_id')}.png"),
                sc.get("video_file") or "",
                sc.get("image_prompt", ""),
                sc.get("video_prompt") or "",
                sc.get("text_overlay_content") or sc.get("overlay_text") or "",
                json.dumps(sc.get("image_motion", {})),
            ])

    # Save reports/ep001_v9_3_1_visual_migration.json
    rep_dir = Path(reports_dir) if reports_dir else Path("reports")
    rep_dir.mkdir(parents=True, exist_ok=True)
    report_file = rep_dir / "ep001_v9_3_1_visual_migration.json"

    migration_report = {
        "episode_id": "EP001",
        "migration_target": "V9.3.1_HYBRID_VISUAL",
        "total_scenes": len(classified_scenes),
        "existing_images_preserved": len(classified_scenes),
        "image_regeneration_count": 0,
        "video_generation_requests": 0,
        "flow_requests": 0,
        "production_summary": manifest_v9_3_1["production_summary"],
        "manifest_path": str(out_manifest),
        "prompts_csv_path": str(out_csv),
    }

    with open(report_file, "w", encoding="utf-8") as f:
        json.dump(migration_report, f, ensure_ascii=False, indent=2)

    logger.info(f"[ProductionAdapter] Migrated EP001 to V9.3.1. Saved {out_manifest} and {report_file}")
    return migration_report
