"""Production Adapter for Script Factory V1.

Converts approved scripts and story bibles into broadcast-ready V9.3 production projects:
- Creates episodes/EPXXX/production/episode_v9_3.json (Schema 3.2, 100% compatible with EP001).
- Generates visual_manifest.json with 35–50 narrative-grounded cinematic scenes.
- Exports visual_prompts.csv, character_bible.json, location_bible.json.
- Initializes manual_assets/images/ and manual_assets/videos/ folders.
- Preserves overlay_text for critical facts and documents (delegated to post-production rendering).
- STRICT SAFETY: NEVER mutates Audio Formula V1 or existing audio engine.
"""
from __future__ import annotations

import csv
import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

from apps.script_factory.approval_gate import HumanApprovalGate
from apps.script_factory.models import ApprovalStatus, FullScript, StoryBible

logger = logging.getLogger("VieNeu.ProductionAdapter")

VISUAL_PROMPT_PREFIX = (
    "Vietnamese cinematic social mystery drama, photorealistic, natural Vietnamese faces, "
    "realistic skin, restrained acting, modern Vietnamese environment, muted natural colors, "
    "subtle cinematic lighting, 35mm documentary drama look, 16:9, no fantasy, no anime, "
    "no glamour, no watermark."
)


class ProductionAdapter:
    """Adapts approved scripts into V9.3-compatible production projects."""

    def __init__(self, episodes_root: Optional[Path] = None):
        self.episodes_root = Path(episodes_root) if episodes_root else Path("episodes")

    def adapt_to_v9_3_project(
        self,
        script: FullScript,
        story_bible: StoryBible,
    ) -> Path:
        """Converts an approved script to a V9.3 production directory."""
        # Enforce approval gate
        HumanApprovalGate.verify_can_send_to_production(script, story_bible)

        ep_dir = self.episodes_root / script.episode_id
        prod_dir = ep_dir / "production"
        prod_dir.mkdir(parents=True, exist_ok=True)

        images_dir = prod_dir / "manual_assets" / "images"
        videos_dir = prod_dir / "manual_assets" / "videos"
        output_dir = prod_dir / "output"
        images_dir.mkdir(parents=True, exist_ok=True)
        videos_dir.mkdir(parents=True, exist_ok=True)
        output_dir.mkdir(parents=True, exist_ok=True)

        # 1. Build episode_v9_3.json (Schema 3.2)
        v9_3_data = {
            "schema_version": "3.2",
            "project": {
                "title": f"Sau Cánh Cửa {script.episode_id} V9.3 Manual Visual",
                "episode_title": script.title,
                "language": "vi-VN",
                "tts_engine": "VieNeu-TTS-v3-Turbo",
                "sample_rate": 48000,
                "target_master_lufs": -14,
                "true_peak_db": -1,
                "format": "single_host_dynamic_documentary_storytelling",
                "target_duration_minutes": "10-13",
                "notes": f"Generated by Script Factory V1 from Story Bible {script.episode_id}.",
            },
            "characters": {
                script.host.get("id", "MINH"): {
                    "display_name": script.host.get("display_name", "Minh"),
                    "role": "MC / narrator",
                    "voice": script.host.get("voice", "Binh"),
                    "default_speed": 1.0,
                }
            },
            "audio_direction": {
                "room_tone": {"enabled": False},
                "voice_rule": f"Only {script.host.get('id', 'MINH')}/{script.host.get('voice', 'Binh')} for every segment.",
                "quote_rule": "Same voice for quotes; vary delivery/pause only, no pitch-shift.",
                "audience_rule": "Conversational and restrained.",
                "critical_reveal_rule": "Major reveal remains fully dry.",
                "music_strategy": "Sparse; continuous within same cue.",
                "dynamic_rule": "Dynamics come primarily from delivery speed, pauses, performance and sparse music—not large loudness jumps.",
                "master_target": "-14 LUFS integrated target, -1 dBTP true peak; preserve natural phrase dynamics before final loudnorm.",
                "profile_order": "HOOK -> NORMAL/MYSTERY/COMMENT -> REVEAL -> NORMAL -> ENDING",
                "reveal_rule": "All REVEAL segments are dry. Music must fade out before the first REVEAL line and may return only after the reveal block.",
            },
            "segments": [s.to_dict() for s in script.segments],
        }

        v9_3_file = prod_dir / "episode_v9_3.json"
        with open(v9_3_file, "w", encoding="utf-8") as f:
            json.dump(v9_3_data, f, ensure_ascii=False, indent=2)

        # 2. Build Visual Manifest (35 to 50 scenes, grouping segments)
        scenes = self._generate_visual_scenes(script, story_bible)
        manifest_data = {
            "manifest_version": "9.3",
            "episode_id": script.episode_id,
            "title": script.title,
            "total_scenes": len(scenes),
            "scenes": scenes,
        }
        manifest_file = prod_dir / "visual_manifest.json"
        with open(manifest_file, "w", encoding="utf-8") as f:
            json.dump(manifest_data, f, ensure_ascii=False, indent=2)

        # 3. Export visual_prompts.csv
        prompts_csv = prod_dir / "visual_prompts.csv"
        with open(prompts_csv, "w", encoding="utf-8", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["scene_id", "image_file", "video_file", "image_prompt", "video_prompt", "overlay_text"])
            for sc in scenes:
                writer.writerow([
                    sc["scene_id"],
                    sc["image_file"],
                    sc["video_file"],
                    sc["image_prompt"],
                    sc["video_prompt"],
                    sc.get("overlay_text") or "",
                ])

        # 4. Copy character and location bibles
        char_file = ep_dir / "character_bible.json"
        if char_file.exists():
            (prod_dir / "character_bible.json").write_text(char_file.read_text(encoding="utf-8"), encoding="utf-8")

        loc_file = ep_dir / "location_bible.json"
        if loc_file.exists():
            (prod_dir / "location_bible.json").write_text(loc_file.read_text(encoding="utf-8"), encoding="utf-8")

        # 5. Record production.json in episode root
        prod_meta = {
            "episode_id": script.episode_id,
            "status": ApprovalStatus.PRODUCTION_READY,
            "production_dir": str(prod_dir),
            "episode_v9_3_json": str(v9_3_file),
            "visual_manifest_json": str(manifest_file),
            "total_scenes": len(scenes),
            "total_segments": len(script.segments),
        }
        with open(ep_dir / "production.json", "w", encoding="utf-8") as f:
            json.dump(prod_meta, f, ensure_ascii=False, indent=2)

        logger.info(f"[ProductionAdapter] Created V9.3 production package for {script.episode_id} with {len(scenes)} visual scenes.")
        return prod_dir

    def _generate_visual_scenes(self, script: FullScript, story_bible: StoryBible) -> List[Dict[str, Any]]:
        """Groups 80-100 segments into 35-50 cinematic visual scenes."""
        segs = script.segments
        total_segs = len(segs)

        # Target ~40 scenes (roughly 2 segments per scene)
        scenes: List[Dict[str, Any]] = []
        step = 2 if total_segs <= 85 else 2
        seg_idx = 0
        scene_idx = 1

        loc_candidates = story_bible.locations if story_bible.locations else ["HOME", "STREET", "OFFICE"]
        protagonist_name = story_bible.protagonist.get("name", "Nhân vật chính")

        while seg_idx < total_segs:
            chunk = segs[seg_idx : min(total_segs, seg_idx + 2)]
            chunk_ids = [s.id for s in chunk]
            beat_text = chunk[0].text[:80] + ("..." if len(chunk[0].text) > 80 else "")

            sc_id = f"SC_{scene_idx:03d}"
            loc = loc_candidates[(scene_idx - 1) % len(loc_candidates)]

            # Check if this scene represents a critical reveal or document
            overlay_text = None
            is_reveal_chunk = any(s.delivery_profile == "REVEAL" for s in chunk)
            if is_reveal_chunk:
                for fact in story_bible.critical_facts:
                    if fact.status == "LOCKED" and (fact.value.lower() in chunk[0].text.lower() or (len(chunk) > 1 and fact.value.lower() in chunk[1].text.lower())):
                        overlay_text = f"{fact.field}: {fact.value}"
                        break
                if not overlay_text and story_bible.reveal_1 in chunk[0].text:
                    overlay_text = f"Xác nhận: {story_bible.reveal_1[:40]}"

            img_prompt = (
                f"{VISUAL_PROMPT_PREFIX} "
                f"Scene {sc_id} set in {loc}. "
                f"Protagonist {protagonist_name} ({story_bible.protagonist.get('age', 32)} years old, authentic domestic look). "
                f"Cinematic framing capturing emotional restraint and domestic mystery. 16:9 composition."
            )

            vid_prompt = (
                f"Slow deliberate camera movement in {loc}. "
                f"Subject subtly shifts posture, reflecting internal tension. "
                f"Preserve exact character identity and lighting. No erratic motion."
            )

            scene_entry = {
                "scene_id": sc_id,
                "source_segments": chunk_ids,
                "story_beat": beat_text,
                "visible_characters": [story_bible.protagonist.get("char_id", "PROTAGONIST")],
                "location": loc,
                "image_file": f"{sc_id}.png",
                "video_file": f"{sc_id}.mp4",
                "image_prompt": img_prompt,
                "video_prompt": vid_prompt,
                "overlay_text": overlay_text,
            }
            scenes.append(scene_entry)

            scene_idx += 1
            seg_idx += len(chunk)

        return scenes
